import { motion } from "framer-motion";
import { Mail, Phone, MapPin, Sparkles } from "lucide-react";
import schedulingConfig from "../config/scheduling";
import Seo from "../components/Seo";
import { siteMeta } from "../config/seo";

const contactInfo = [
  {
    icon: Mail,
    label: "Email",
    value: "youbakrzaki@gmail.com",
    href: "mailto:youbakrzaki@gmail.com",
  },
  {
    icon: Phone,
    label: "Phone",
    value: "+20 (111) 284 9384",
    href: "tel:+201112849384",
  },
  {
    icon: MapPin,
    label: "Location",
    value: "Based in Egypt / Remote worldwide",
  },
];

const collaborationNotes = [
  "LMS, simulation, or SaaS builds blending React/Next.js with Node.js or Express.js services",
  "RESTful + GraphQL API modernization, SQL/MongoDB migrations, or systems analysis retainers",
  "Realtime Socket.io, Kafka, or telemetry-heavy initiatives needing reliability audits",
  "AWS, Docker, and Kubernetes automation plus developer experience coaching for platform teams",
];

const availability = [
  { day: "Monday", slots: "09:00 — 13:00 GMT" },
  { day: "Tuesday", slots: "09:00 — 13:00 GMT" },
  { day: "Wednesday", slots: "09:00 — 13:00 GMT" },
  { day: "Thursday", slots: "09:00 — 13:00 GMT" },
  { day: "Friday", slots: "On request" },
];

const LetsTalk = () => {
  const bookingUrl = schedulingConfig.bookingUrl;
  const bookingSchema = [
    {
      "@type": "WebPage",
      "@id": `${siteMeta.siteUrl}/lets-talk`,
      url: `${siteMeta.siteUrl}/lets-talk`,
      name: "Book a project chat with Yousef Bakr",
      description:
        "Schedule a discovery call with software engineer and systems analyst Yousef Bakr. Share LMS, simulation, SaaS, or API requirements and receive a tailored plan.",
    },
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: `${siteMeta.siteUrl}/`,
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Contact",
          item: `${siteMeta.siteUrl}/contact`,
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "Let's Talk",
          item: `${siteMeta.siteUrl}/lets-talk`,
        },
      ],
    },
    {
      "@type": "Service",
      name: "Product discovery call",
      areaServed: "Worldwide",
      provider: {
        "@type": "Person",
        name: "Yousef Bakr",
      },
      availableChannel: {
        "@type": "ServiceChannel",
        availableLanguage: ["English", "Arabic"],
        serviceUrl: `${siteMeta.siteUrl}/lets-talk`,
      },
    },
  ];

  return (
    <>
      <Seo
        title="Let's Talk"
        description="Book a call with Yousef Bakr to discuss software architecture, LMS launches, simulation systems, API and data roadmaps, or AWS/Docker/Kubernetes automation."
        keywords={[
          "book yousef bakr",
          "schedule software engineering consultation",
          "LMS discovery call",
          "full-stack project kickoff",
        ]}
        url="/lets-talk"
        schema={bookingSchema}
      />
      <div className="bg-slate-950 text-white">
        <section className="px-6 pt-24 pb-12 sm:px-10 lg:px-16">
          <div className="grid gap-8 rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 to-slate-950 p-6 shadow-2xl shadow-slate-900/40 lg:grid-cols-[1fr,1fr] lg:p-10">
          <motion.div
            className="space-y-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <p className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs uppercase tracking-[0.4em] text-sky-300">
              <Sparkles size={16} />
              Let&apos;s Talk
            </p>
            <h1 className="text-4xl font-semibold leading-tight sm:text-5xl">
              Pick a slot, and I&apos;ll send the Meet or Zoom invite.
            </h1>
            <p className="text-slate-300">
              Use the scheduler to choose a time that works best for deep dives into LMS builds, simulation control rooms, API modernization, data migrations, or AWS/Docker/Kubernetes automation. Once it&apos;s confirmed, you will receive a calendar invite with the video conference link automatically generated by the booking service.
            </p>
            <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
              <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                Collaboration fit
              </p>
              <ul className="mt-4 space-y-3 text-sm text-slate-300">
                {collaborationNotes.map((note) => (
                  <li key={note} className="flex items-start gap-3">
                    <span className="mt-1 h-2 w-2 rounded-full bg-sky-300" />
                    {note}
                  </li>
                ))}
              </ul>
            </div>
          </motion.div>

          <motion.div
            className="rounded-3xl border border-white/10 bg-white/5 p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            <h2 className="text-xl font-semibold text-white">
              Weekly availability
            </h2>
            <p className="mt-2 text-sm text-slate-300">
              Pick a slot below. The scheduler handles time zones and sends the
              Google Meet link once confirmed. All hours are shown in GMT.
            </p>
            <div className="mt-4 grid gap-3 text-sm text-slate-200 sm:grid-cols-2">
              {availability.map((slot) => (
                <div
                  key={slot.day}
                  className="rounded-2xl border border-white/10 bg-white/5 p-3"
                >
                  <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                    {slot.day}
                  </p>
                  <p className="text-lg font-semibold text-white">
                    {slot.slots}
                  </p>
                </div>
              ))}
            </div>
            <p className="mt-4 text-xs text-slate-400">
              Need a different time zone? Mention it and I&apos;ll attempt to
              accommodate.
            </p>
            <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-2">
              {bookingUrl ? (
                <iframe
                  title="Schedule a call"
                  src={bookingUrl}
                  className="h-[540px] w-full rounded-2xl border-0"
                  loading="lazy"
                />
              ) : (
                <div className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-slate-300">
                  Provide `VITE_SCHEDULER_URL` in your .env to embed your booking
                  widget (Calendly, Cal.com, etc.). Until then, use the contact
                  form below to request a time.
                </div>
              )}
            </div>
            {!bookingUrl && (
              <div className="mt-4 text-sm text-slate-400">
                <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                  Manual request
                </p>
                <p className="mt-2">
                  Fill out the form and I&apos;ll coordinate a slot manually with a
                  Google Meet link.
                </p>
              </div>
            )}
          </motion.div>
        </div>
      </section>

      <section className="px-6 pb-12 sm:px-10 lg:px-16">
        <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
          <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
            Need a bespoke time?
          </p>
          <p className="mt-3 text-sm text-slate-300">
            If none of the available windows work, or you need to coordinate
            under NDA, message me via the{" "}
            <a
              href="/contact"
              className="text-sky-300 underline underline-offset-4"
            >
              contact page
            </a>
            . I&apos;ll propose alternatives manually and send a Meet/Zoom link
            once we agree on a slot.
          </p>
        </div>
      </section>

      <section className="px-6 pb-16 sm:px-10 lg:px-16">
        <div className="grid gap-6 lg:grid-cols-3">
          {contactInfo.map((item) => {
            const Icon = item.icon;
            return (
              <motion.div
                key={item.label}
                className="rounded-3xl border border-white/10 bg-white/5 p-6"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{ duration: 0.5 }}
              >
                <div className="flex items-center gap-3">
                  <span className="rounded-2xl bg-white/10 p-2 text-sky-300">
                    <Icon size={18} />
                  </span>
                  <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                    {item.label}
                  </p>
                </div>
                {item.href ? (
                  <a
                    href={item.href}
                    className="mt-4 block text-lg font-semibold text-white hover:text-sky-300"
                  >
                    {item.value}
                  </a>
                ) : (
                  <p className="mt-4 text-lg font-semibold text-white">
                    {item.value}
                  </p>
                )}
              </motion.div>
            );
          })}
        </div>
      </section>
    </div>
  </>
  );
};

export default LetsTalk;
